package vistas;

import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author KYUZAMG
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        setTitle("Tienda de Libros Vintage");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        jMenuItemVender = new javax.swing.JMenuItem();
        jMenuItemTransaccion = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCaja = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemCliente = new javax.swing.JMenuItem();
        jMenuItemProveedores = new javax.swing.JMenuItem();
        jMenuItemLibros = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(153, 0, 51));
        lblTitulo.setText("Tienda de Libros Vintage");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Libros.jpg"))); // NOI18N

        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu.png"))); // NOI18N

        jMenuItemVender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/shopping.png"))); // NOI18N
        jMenuItemVender.setText("Vender");
        jMenuItemVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVenderActionPerformed(evt);
            }
        });
        Menu.add(jMenuItemVender);

        jMenuItemTransaccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/transaction.png"))); // NOI18N
        jMenuItemTransaccion.setText("Transacciones");
        Menu.add(jMenuItemTransaccion);
        Menu.add(jSeparator1);

        jMenuItemCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja.png"))); // NOI18N
        jMenuItemCaja.setText("Caja");
        Menu.add(jMenuItemCaja);

        menuBar.add(Menu);

        jMenu1.setText("Datos");

        jMenuItemCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/persona.png"))); // NOI18N
        jMenuItemCliente.setText("Clientes");
        jMenuItemCliente.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                jMenuItemClienteMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMenuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCliente);

        jMenuItemProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/proveedorIcono.png"))); // NOI18N
        jMenuItemProveedores.setText("Proveedores");
        jMenuItemProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProveedoresActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemProveedores);

        jMenuItemLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/libroIcono.png"))); // NOI18N
        jMenuItemLibros.setText("Libros");
        jMenu1.add(jMenuItemLibros);

        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemClienteActionPerformed

    private void jMenuItemProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProveedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemProveedoresActionPerformed

    private void jMenuItemClienteMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jMenuItemClienteMenuKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItemClienteMenuKeyPressed

    private void jMenuItemVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemVenderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu Menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    public javax.swing.JMenuItem jMenuItemCaja;
    public javax.swing.JMenuItem jMenuItemCliente;
    public javax.swing.JMenuItem jMenuItemLibros;
    public javax.swing.JMenuItem jMenuItemProveedores;
    public javax.swing.JMenuItem jMenuItemTransaccion;
    public javax.swing.JMenuItem jMenuItemVender;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblTitulo;
    public javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
}
